### ISSUE TITLE
Missing swap declaration in unique_ptr example with custom deleter (sect. 4.9)

### ISSUE THREAD

**Issue by gnzlbg** [slurps-mad-rips/retain-ptr#1]
In `4.9   Why not just wrap a unique_ptr with a custom deleter?` the example for using `std::unique_ptr` with a custom deleter calls a `.swap` member function in the `context` object in line 27, but this member function is never declared.

EDIT: maybe `std::swap` was meant?

**Comment by bruxisma** [comment]
This is in fact a typo.

**Comment by bruxisma** [comment]
This has been fixed.
