### ISSUE TITLE
Why are the default counts `uint_least64_t` ?

### ISSUE THREAD

**Issue by gnzlbg** [slurps-mad-rips/retain-ptr#2]
The default counts in `atomic_reference_count<T>` and `reference_count<T>` are of type `uint_least64_t` but there is no rationale for this decision in the paper. In particular:
- Why isn't 32 bit enough? (e.g. why not use `uint_least32_t` ?),
- Why isn't it easily customizable? (e.g. `atomic_reference_count<T, C = uint_least64_t>`?).

**Comment by bruxisma** [comment]
There is no reason other than they are shown as exposition. If you look at the implementation, you'll note that I use `long` and `std::atomic<long>`

**Comment by gnzlbg** [comment]
That makes sense. Maybe adding an inline comment in the example would make this clear (e.g. `// exposition only (see implementation)`). I'll take a look at the implementation of the examples.

**Comment by bruxisma** [comment]
Well that is why it says `// provided for exposition` after each declaration. :v

**Comment by gnzlbg** [comment]
!! completely missed that, my bad! (was it always there? :laughing: )

**Comment by bruxisma** [comment]
They were! I've definitely learned some people are missing a sentence or two while reading this proposal (and that I did as well when proofreading)

**Comment by gnzlbg** [comment]
I could blame this on coffee not having kicked in yet but with the comment next to it there is no good excuse. Good work with the proposal, I've enjoyed reading it.

**Comment by bruxisma** [comment]
Thanks! Glad you enjoyed it :)
