### ISSUE TITLE
Missing declarations in "future"s example

### ISSUE THREAD

**Issue by gnzlbg** [slurps-mad-rips/retain-ptr#3]
- `atomic_reference_counter` is missing
- `rethrow_exception` is missing
- `promise<T>` calls `this->state.template emplace` but `state` is of type `retain_ptr<shared_state<T>>`  which doesn't have an `emplace` method (maybe it is missing in `shared_state<T>`?)

Then the `retain_ptr` is constructed by default as `retain_ptr<shared_state<T>> state { new shared_state<T>() };`. Is there a way to avoid using `new` here? Not that is bad per se, but I am missing rationale for a lack of `make_retain` function in the spirit of `make_unique/shared`.

**Comment by bruxisma** [comment]
The futures example was more or less taken from a small quick slide on Gor Nishanov's coroutine talk. The `template emplace` is supposed to be on the state object's variant type. Whoops!

**Comment by bruxisma** [comment]
`atomic_reference_counter` is part of the specification
`rethrow_exception` is part of the standard library
I fixed the call to `emplace`.

I need more feedback on the general interface of `retain_ptr` before I commit to adding a `make_retain`, as there would not be an easy way to declare a traits type when calling it, and it would then be useful only for types that inherit from `atomic_reference_count` or `reference_count`.

If you think a `make_retain` should be part of the interface, please make a separate issue.
